### ISSUE TITLE
User Auth Review

### ISSUE THREAD

**Issue by ghu-ut** [ghu-ut/AllTreks#1]

**Comment by vawhitehouse** [comment]
Really nice job! Here's a few things to help get it pixel perfect:

- [ ] Styling on Sign Up/Log In buttons is reversed - Sign Up should be filled out, Log In should be outlined
- [ ] Button text should a slightly heavier font weight
- [ ] The logo/title in the navbar should link to the home page - I know it seems a bit weird when you're already on the home page but you'll likely be rendering the this navbar across the site. And right now it looks like a dead dead link since on hover the cursor is a pointer but you can't click. 
- [ ] Form inputs/placeholder text color looks darker than AllTrails
- [ ] We want all the session errors to render exactly as the do on AllTrails - input field outlined in red, relevant error directly below
- [ ] The placeholder text should raise to be inline with the input outline when you click in the field. 
- [ ] I would drop the 'for free' in "Sign up for free"
- [ ] Session form errors aren't being cleared when you switch between forms

**Comment by vawhitehouse** [comment]
- [ ] You also need a demo log in
